/* eslint-disable import/no-anonymous-default-export */
export default {
	CREATE_COURSE: "CREATE_COURSE",
	LOAD_COURSES: "LOAD_COURSES",
	UPDATE_COURSE: "UPDATE_COURSE",
	DELETE_COURSE: "DELETE_COURSE",
	CREATE_AUTHOR: "CREATE_AUTHOR",
	LOAD_AUTHOR: "LOAD_AUTHOR",
	UPDATE_AUTHOR: "UPDATE_AUTHOR",
	DELETE_AUTHOR: "DELETE_AUTHOR",
}
